### ISSUE TITLE
Not printing text

### ISSUE THREAD

**Issue by marvoh** [applicius/dhek#212]
I've used the php example as on the website and while it handles checkboxes well, it draws all rectangles for textboxes but no text is being printed in them.

I have tried multiple printing fuctions like:

```
$pdf->MultiCell($w, intval($h), $v, true);

$pdf->Write(intval($h),$v);

$pdf->Cell($w, intval($h), $v, true);
```

**Comment by cchantep** [comment]
Hi,

PHP examples are provided as-is. Many error can occurs with the PHP/PDF lib. I suggest you check that.

Best regards.
