### ISSUE TITLE
Maybe not is a issue, just a contact

### ISSUE THREAD

**Issue by AlexVFornazieri** [applicius/dhek#213]
Hello everyone, I found the idea of Dhek project fascinating, and want to use it in my projects, I love making amazing PDF templates for reports, but making the system fill this is an impossible task, but this project seems to make it much easier.
But I have a question, is anyone aware of any implementation of this on linux systems, using Python or Java? Because these are the technologies that I work, because if you have not, I take to start this work! XD

**Comment by cchantep** [comment]
Dhek is not a PDF generator, but a tool to prepare a JSON template, usable on whatever modern env.
